site_name: Cyberflix - Docs
site_description: The official documentation for the Cyberflix Media Center.
site_author: BobDaGecko
site_url: https://docs.cyberflix.io/

repo_url: https://github.com/BobDaGecko/Cyberflix-Docs
repo_name: BobDaGecko/Cyberflix-Docs

theme:
  name: material
  palette:
    scheme: slate
  favicon: img/favicon.png
  logo: img/logo.png

copyright: Copyright &copy; 2021 Cyberflix Media. All rights reserved.

nav:
    - Home: index.md
    - About:
        - Release Notes: about/terms-and-conditions.md
        - Contributing: about/privacy-policy.md
        - License: about/license.md

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.highlight
  - toc:
      permalink: true
      toc_depth: 5
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
