site_name: Cyberflix - Docs
site_description: The official documentation for the Cyberflix Media Center.
site_author: BobDaGecko

repo_url: https://github.com/BobDaGecko/Cyberflix-Docs
repo_name: BobDaGecko/Cyberflix-Docs

theme:
  name: material

copyright: Copyright &copy; 2021 Cyberflix Media. All rights reserved.
